### ISSUE TITLE
`pre-commit run -a` outputs different result to `gitleaks --repo-url .`

### ISSUE THREAD

**Issue by tumido** [zricethezav/gitleaks#657] opened 2021-10-08 12:13 UTC
**Describe the bug**
Pre-commit's `run --all-files` should check on all files in the repo, including those which are already commited. `gitleaks` hook disregards already commited files and does not check them.

**To Reproduce**

1. Have a pre-commit hook enabled
```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
      - id: gitleaks
        args: ["--verbose"]
```

2. Have a file with any secret violation e.g.:
```
AKIA0000000000000000
```
3. Commit the file (skipping pre-commit or disabling it)
4. Run `pre-commit run -a` and see that it passed without detecting any violation
5. Run `gitleaks --repo-url .` and see that it detected the violation properly

**Expected behavior**
I expect the `pre-commit run -a` with `gitleaks` hook to behave in the same way as `gitleaks --repo-url .`

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/136554911-aedb29ce-2296-4a1f-b698-e152be2e9d66.png)

**Basic Info (please complete the following information):**
 - OS: linux
 - Gitleaks Version: 7.6.1

**Additional context**
If `gitleaks` skips detection of secrets on already commited files, it's harder to introduce `gitleaks` hook as a new hook to existing repo. Because that's what pre-commit users do, when they add new hooks or upgrade them - they run the new hooks against all files to fix everything up. 

cc @zricethezav

**Comment by w0rmr1d3r** [comment] 2021-10-08 13:05
Hello @tumido !

Can you pass as arguments to the pre-commit the same arguments you are passing to the execution of gitleaks outside the pre-commit?
That is:
```
args: ["--verbose --repo-url ."]
```
And re-run the tests you've done to find the bug?

I believe the pre-commit configuration might need some arguments by default that we aren't passing them.

Thank you!

**Comment by tumido** [comment] 2021-10-11 06:53
Hey @w0rmr1d3r,

I think the problem is caused by `gitleaks` not consuming the `--all-files` flag from pre-commit (not sure how the integration is supposed to works at all, that's just my observation).

To demostrate, I've changed the pre-commit config to (per your suggestion). This results in:

1. `pre-commit` to always fail on empty repo (but that's not an issue, just a side effect here, I don't care about that)
2. It makes `gitleaks` to execute against commited changes only every time, no matter if `--all-files` flag is passed or not or if files are staged or not:

```sh
$ git init 
Initialized empty Git repository in /tmp/test/.git/

$ cat <<EOM > .pre-commit-config.yaml
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
      - id: gitleaks
        args: [--repo-url, .]
EOM

$ git add .

$ git status
## No commits yet on main
A  .pre-commit-config.yaml

$ pre-commit install
pre-commit installed at .git/hooks/pre-commit

$ git commit -m "init"
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1

INFO[0000] cloning... .
ERRO[0000] remote repository is empty

$ pre-commit uninstall  # <-- skip pre-commit due to empty repository (see no. 1 above)
pre-commit uninstalled

$ git commit -m "init"
[main (root-commit) ac9804a] init
 1 file changed, 6 insertions(+)
 create mode 100644 .pre-commit-config.yaml

$ pre-commit install
pre-commit installed at .git/hooks/pre-commit

$ echo "AKIA0000000000000000" > awsKeyId

$ git status  # <-- awsKeyId is left unstaged for now
## main
?? awsKeyId

$ pre-commit run  # <-- this is correct, because the leak is NOT staged
Detect hardcoded secrets.............................(no files to check)Skipped

$ pre-commit run -a # <-- this should fail because the leak is present on the filesystem
Detect hardcoded secrets.................................................Passed

$ gitleaks --repo-url .  # <--  this behaves properly since the leak is not committed
INFO[0000] cloning... .
INFO[0000] scan time: 351 microseconds
INFO[0000] commits scanned: 1
INFO[0000] No leaks found

$ gitleaks  # <-- this is correct, since the leak is NOT staged
INFO[0000] opening .
INFO[0000] scan time: 3 milliseconds 551 microseconds
INFO[0000] No leaks found

$ git add .

$ git status  # <--- awsKeyId is staged
## main
A  awsKeyId

$ pre-commit run  # <-- this should fail because the leak is staged
Detect hardcoded secrets.................................................Passed

$ pre-commit run -a  # <-- this should fail because the leak is present on the filesystem
Detect hardcoded secrets.................................................Passed

$ gitleaks --repo-url .  # <-- this behaves properly since the leak is not committed
INFO[0000] cloning... .
INFO[0000] scan time: 257 microseconds
INFO[0000] commits scanned: 1
INFO[0000] No leaks found

$ gitleaks  # <-- this is correct, since the leak is staged
INFO[0000] opening .
INFO[0000] scan time: 6 milliseconds 458 microseconds
WARN[0000] leaks found: 1

$ git commit -m "test"  # <-- this should fail, because the leak is staged
Detect hardcoded secrets.................................................Passed
[main a4f3b3e] test
 1 file changed, 1 insertion(+)
 create mode 100644 awsKeyId

$ gitleaks --repo-url .  # <-- this is correct because the leak is commtited
INFO[0000] cloning... .
INFO[0000] scan time: 549 microseconds
INFO[0000] commits scanned: 2
WARN[0000] leaks found: 1

$ gitleaks  # <-- this is correct because the leak is not staged
INFO[0000] opening .
INFO[0000] scan time: 5 milliseconds 494 microseconds
INFO[0000] No leaks found

$ pre-commit run  # <-- this is correct because there's no staged files
Detect hardcoded secrets.............................(no files to check)Skipped

$ pre-commit run -a  # <-- this is correct because the leak is committed
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1

INFO[0000] cloning... .
INFO[0000] scan time: 391 microseconds
INFO[0000] commits scanned: 2
WARN[0000] leaks found: 1
```

I think this is not expected bahavior of `pre-commit`, the default configuration is definitely much better than this.

I think the problem is that `gitleaks` is not consuming context from `pre-commit`.

`gitleaks` command by default acts on staged changes in the current repo. That is consistent with expected behavior of `pre-commit run` (which is the same as the hook executed before `git commit`).

However the `gitleaks` behavior stays the same even if it's called via `pre-commit run --all-files`. In that case `gitleaks` is still looking up the staged files only, while users (as well as `pre-commit`) expect it to run the check against the repo as a whole (that means unstaged + staged + all history), basically disregarding that it's a git repo and looking at the files as they are.

**Comment by danielorihuela** [comment] 2021-10-14 16:25
I have made a POC that changes the behaviour to match the pre-commit run and pre-commit run -a.
@tumido You can check it here https://github.com/danielorihuela/gitleaks/tree/fix/gitleaks-behaviour-on-pre-commit-run.

If you need to use it, you can fork it to use in your pre-commits.

@zricethezav @w0rmr1d3r I am willing to work on that if the POC makes sense.

**Comment by danielorihuela** [comment] 2021-10-19 17:11
@w0rmr1d3r Opened. If the solution makes sense, we can work on improvements, refactor and tests.

**Comment by zricethezav** [comment] 2021-12-16 14:09
closing, pre-commit is working as intended https://asciinema.org/a/455683

**Closed by zricethezav** 2021-12-16 14:09 UTC
Labels: bug

**Comment by Sicks3c** [comment] 2022-08-20 20:25
Hey 

Is `--repo-url` depressed ? 
What's the alternative in latest version ?

Cheers
