### ISSUE TITLE
Regex for allowlist is not work effecienly

### ISSUE THREAD

**Issue by tientmse62290** [zricethezav/gitleaks#882] opened 2022-06-01 07:30 UTC
**Describe the bug**
I add to the [allowlist]
regrexes = ['''(.*?)(public|Public)(.*?)''']
![image](https://user-images.githubusercontent.com/28757980/171351151-41c67deb-b4a3-4dc2-b2cc-f40c52bad290.png)

but it wasn't overriding the rule for generic-api-key

**To Reproduce**
content:
```
`<property path="/name" isComplexType="false" isExplicitlyDefined="true" clrType="System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">`
```

**Expected behavior**
gitleaks = 0
output file shows a lot that is duplicate and just shows a part of the value pair: "KeyToken" instead of "PublicKeyToken"
it shouldn't be show in the output file
![image](https://user-images.githubusercontent.com/28757980/171350463-de1d24e9-32aa-4aad-a49e-04bac6731ea9.png)

**Basic Info (please complete the following information):**
 - OS: Kali 2022.2
 - Gitleaks Version: 
 - REPOSITORY             TAG       IMAGE ID       CREATED      SIZE
zricethezav/gitleaks   latest    1b2a4d9ec5d4   3 days ago   34.5MB

cc @zricethezav

**Comment by zricethezav** [comment] 2022-06-01 12:09
Hi @tientmse62290 this isn't a bug since the generic rule is matching on `PublicKeyToken=b77a5c561934e089`. When it comes time to check the allowlist, the only context gitleaks has is `PublicKeyToken=b77a5c561934e089`, not the entire line. If you want to ensure gitleaks ignores a line you can add a comment like `// gitleaks:allow`. 

I'm open to hearing ideas on adding an option for the allowlist to include the whole line but that would be a feature request and not a bug. I'm going to close this issue for now.

**Closed by zricethezav** 2022-06-01 12:09 UTC
Labels: bug
