### ISSUE TITLE
v2.1.0 is not available on the DockerHub

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#259] opened 2019-09-06 00:11 UTC
https://hub.docker.com/r/zricethezav/gitleaks/tags does not seem to have v2.1.0
It is suggested that there is v2.1.0, as per https://github.com/zricethezav/gitleaks/releases page

**Comment by Chan9390** [comment] 2020-03-02 17:25
Looks like the issue is solved as we have latest release on Dockerhub (latest version 4.0.1 at the time of commenting).

**Comment by zricethezav** [comment] 2020-03-10 14:03
closing this issue

**Closed by zricethezav** 2020-03-10 14:03 UTC
