### ISSUE TITLE
Feature Request: Line Number 

### ISSUE THREAD

**Issue by gjohnson** [zricethezav/gitleaks#203] opened 2019-05-06 11:42 UTC
Thoughts on adding the line number and start/end column of the match to the output? The use case would be using gitleaks within a [Check Suite, including annotations](https://developer.github.com/v3/checks/runs/#annotations-object-1).

**Comment by zricethezav** [comment] 2019-05-28 21:45
That would be a useful addition to the report but unfortunately the git library I use does not support line numbers in their patches -- or at least I'm not aware of it

**Comment by avishnyakov** [comment] 2019-09-07 01:34
This can be useful. Having line number in the output would help to produce the right URL link to the GitHub or other repository straight away - to the commit, file and even line!

**Comment by dorneanu** [comment] 2020-01-07 13:54
I agree with @gjohnson: Having the line number in-place will help generating check run annotations.

**Comment by hamoriz** [comment] 2020-07-10 06:17
> That would be a useful addition to the report but unfortunately the git library I use does not support line numbers in their patches -- or at least I'm not aware of it

Would not be possible just to count the line breaks in the file? Like

`func inspectFileContents(content string, path string, rule config.Rule, c *object.Commit, repo *Repo) {
	locs := rule.Regex.FindAllIndex([]byte(content), -1)
	if len(locs) != 0 {
		for _, loc := range locs {
			start := loc[0]
			end := loc[1]
			for start != 0 && content[start] != '\n' {
				start = start - 1
			}
			if start != 0 {
				// skip newline
				start = start + 1
			}

			for end < len(content)-1 && content[end] != '\n' {
				end = end + 1
			}

			line := content[start:end]
			offender := content[loc[0]:loc[1]]
			index := strings.Count(content[0:end], "\n")`

**Comment by zricethezav** [comment] 2020-07-10 12:44
@hamoriz @avishnyakov @dorneanu @gjohnson 

I'm actively working on this issue. See https://github.com/zricethezav/gitleaks/compare/extract-line?expand=1 for the progress. Basically if there is a leak detected, gitleaks will open the file at that commit and search for the line that contains the leak. This has potential to significantly slow down the scan so I'm thinking of making this an optional feature.

Feel free to offer any suggestions or open a PR for this -- I probably won't get to it until next weekend or so

**Comment by zricethezav** [comment] 2020-07-21 17:44
Tracking this work here as well https://gitlab.com/gitlab-org/gitlab/-/issues/230817

**Comment by gjohnson** [comment] 2020-07-22 18:14
This makes sense to me @zricethezav! Good point about the performance implications. I am writing less code these days, otherwise I'd submit a PR 🙃

**Comment by zricethezav** [comment] 2020-07-24 16:23
@hamoriz @avishnyakov @dorneanu @gjohnson
Folks, I just released https://github.com/zricethezav/gitleaks/releases/tag/v5.0.0 which includes adding line numbers to the report. It would be great if some of you could test it out and lemme know whatcha think before closing this issue.

**Comment by steeve85** [comment] 2020-07-24 23:35
This works great! Thank you @zricethezav 
Quick question, I was able to see `-1` as a line number. What is the reason/meaning of this negative line number?

**Comment by zricethezav** [comment] 2020-07-25 00:49
@steeve85 thanks for checking it out :)

`-1` means that the line could not be found when doing a search for it OR the git operation was a deletion in which case the leak does not exist in that file anymore. Was the operation an `addition` or `deletion`. The process of searching for the line number could probably use some refining.

**Comment by steeve85** [comment] 2020-07-25 00:54
In my case it was an `addition`. I will do more testing and open issue/PR if I can reproduce the bug

**Comment by zricethezav** [comment] 2020-07-25 00:56
Thanks! That would be much appreciated.

**Comment by steeve85** [comment] 2020-07-25 03:18
I was able to reproduce the bug within a public repository: https://github.com/zricethezav/gitleaks/issues/413

**Comment by zricethezav** [comment] 2020-07-26 14:08
Gonna close this issue out. Feel free to reopen if you think it's not complete.

**Closed by zricethezav** 2020-07-26 14:08 UTC
