### ISSUE TITLE
Gitleaks not working as expected for long history Commits on Gitlab

### ISSUE THREAD

**Issue by Wankhadess** [zricethezav/gitleaks#976] opened 2022-09-07 06:16 UTC
**Describe the bug**
After adding custom configuration file .toml for excluding the commits. we are still getting the long history issues after providing the required method provided by you it's working fine for excluding the current commits we are getting in the logs at single run but after every run it displays new Issues from past and we have long history it's getting difficult to handle it in multiple consecutive commits. 

Is there any way we can add any parameter in the .toml to exclude all the past History commits? or any alternative options. 
Is there any option to provide range of commits or to ignore the past commits and only considering the latest commits???

**To Reproduce**
Create one custom .toml file see below:
#Title for the gitleaks configuration file.
title = "Gitleaks title"

useDefault = true

[[rules]]
[allowlist]
description = "ignore commit"
commits = [commit1,commit2]

**Expected behavior**
It should ignore the Commit1 and commit2 it works but after that it raises past commits also.

**Basic Info (please complete the following information):**
 - Gitlab Version: Community Edition 15.3.2
 - Gitleaks Version: v8.12.0

cc @zricethezav

**Comment by zricethezav** [comment] 2022-09-16 14:37
@Wankhadess 
> After adding custom configuration file .toml for excluding the commits. we are still getting the long history issues after providing the required method provided by you it's working fine for excluding the current commits we are getting in the logs at single run but after every run it displays new Issues from past and we have long history it's getting difficult to handle it in multiple consecutive commits.

Allowlists to not stop the scan from continuing to look at history. Commits in allowlists instruct gitleaks to ignore those commits. If you want to limit the history of what is scanned then you need to use `--log-opts` which accept any `git log` arguments. https://git-scm.com/docs/git-log

Closing this issue as it is not a bug. You can continue the conversation on this issue even though it is closed.

**Closed by zricethezav** 2022-09-16 14:37 UTC
Labels: bug
