### ISSUE TITLE
[v8.1] unable to scan source path

### ISSUE THREAD

**Issue by llaville** [zricethezav/gitleaks#738] opened 2021-12-04 15:10 UTC
**Describe the bug**
Cannot be able to scan a git clone repository with following docker commands (simple user or root account with sudo)
- `docker run -v $(pwd):/path zricethezav/gitleaks:latest detect`
- `docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --no-git`
- `docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --source .`
- `docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --source $(pwd)`

**To Reproduce**
- i.e : `git clone https://github.com/llaville/docker-php-toolbox.git`, but any other source is also acceptable

**Expected behavior**
Be able to scan source code and detect if there are potential secrets in code

**Screenshots**

![gitleaks](https://user-images.githubusercontent.com/364342/144714570-3111b99c-6cc2-4f75-a9ce-e59c7fbf2d35.png)

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Gitleaks Version: 8.1.0
 - Docker image: `zricethezav/gitleaks                                latest                9f02e9c7adf9   37 hours ago    33.5MB`
 - Docker version: 20.10.11, build dea9396

cc @zricethezav

**Comment by zricethezav** [comment] 2021-12-04 15:23
@llaville you need to do what @nvuillam [suggested](https://github.com/zricethezav/gitleaks/issues/737#issuecomment-986000028)

`docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --source /path`

**Comment by llaville** [comment] 2021-12-04 15:53
![gitleaks_detect_ok](https://user-images.githubusercontent.com/364342/144715810-95581408-e0c6-4f4f-8da6-8c1788e850a3.png)

@zricethezav Ok it works. 
If `--source /path` identify the mount container directory, is this `--source` option really usefull, especially if default as we can read is `-s, --source string          path to source (default: $PWD) (default ".")`

**Comment by llaville** [comment] 2021-12-04 15:57
I don't understand what you means by default, when option requires an argument 

![gitleaks_detect_source](https://user-images.githubusercontent.com/364342/144716078-ab5a4dee-15b1-4888-99b4-7d5283ae8023.png)

**Comment by zricethezav** [comment] 2021-12-04 16:01
@llaville 
`--source` needs an argument

The default argument for `--source` is `.` if `--source` is not set

Using `docker run .... detect --source` results in an error because you have no argument for `--source`

Closing this issue

**Closed by zricethezav** 2021-12-04 16:01 UTC
Labels: bug

**Comment by llaville** [comment] 2021-12-04 16:08
@zricethezav But remember that command `docker run -v $(pwd):/path zricethezav/gitleaks:latest detect` (without `--source` option, then default `.` applied) won't works.

`4:06PM ERR fatal: not a git repository (or any of the parent directories): .git`

**Comment by zricethezav** [comment] 2021-12-04 16:36
@llaville that is fine because the default value for —source is set for ease of use on developers local machines. The documentation is clear, —source must be set when running in docker. This issue is not a bug. Feel free to open a PR if you think the documentation is lacking.
