### ISSUE TITLE
Using unaltered "zricethezav" config toml explicitly, leads somehow to way more findings

### ISSUE THREAD

**Issue by Vankog** [zricethezav/gitleaks#869] opened 2022-05-11 05:55 UTC
**Describe the bug**
We plan to customize some rules. Thus, we naturally started by copying the default config from  
https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml  
and used it via   
`- gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml` 
in our gitlab-ci.yml.

Much to my suprise, the findings went up from 86 to 102.

Gitleaks Version and copied toml do match: 
gitleaks docker image https://hub.docker.com/layers/zricethezav/gitleaks/v8.8.4/images/sha256-3e7186a08439aafd17405c787287ba2d6a1dd88344757c6209b1ce08f0d1be7e?context=explore 
=> v. 8.8.4), 
and toml on master at that time, matching release tag 8.8.4: https://github.com/zricethezav/gitleaks/releases/tag/v8.8.4
Of Course, the analyzed source code is at the same state as well. (except for the gitleaks config, that is)

**To Reproduce**
* Use Gitleaks 8.8.4 docker with `gitleaks detect  -f json --redact -r ./secret-scan-results.json`
* Copy https://github.com/zricethezav/gitleaks/blob/61ee7c58cc00840f2959f46fdf6f1bf860870f41/config/gitleaks.toml   
to /.config/ in your repo.   
(note: I am not sure if the leading dot makes a difference. We need it though. Otherwise gradle thinks this is a sub-project.)
* Use Gitleaks 8.8.4 docker with `gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml`

Unfortunately, I am not able to provide you access to the repo in question. Sorry.

**Expected behavior**
The result should be the same.

**Basic Info (please complete the following information):**
hosted GitLab Community Edition 14.9.2
using gitlab-ci
with gitlab-ci.yml:

```yml
# GitLeaks Secret Scanning
stages:
  - secret-scan

gitleaks:
  stage: secret-scan
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [""]
  script:
    - git config --global --add safe.directory /builds/myGroup/myProject
    - gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - secret-scan-results.json
  timeout: 2 hours
  allow_failure: true

```

 - Gitleaks Version: 8.8.4 docker image, "latest" tag currently being: https://hub.docker.com/layers/zricethezav/gitleaks/v8.8.4/images/sha256-3e7186a08439aafd17405c787287ba2d6a1dd88344757c6209b1ce08f0d1be7e?context=explore

cc @zricethezav

**Comment by Vankog** [comment] 2022-05-11 06:07
Onke strange thing I found is that the results seem to reference the same findings in different commits.    
example:  
a result with default config:

```json
	{
		"Description": "Generic API Key",
		"StartLine": 4,
		"EndLine": 5,
		"StartColumn": 2,
		"EndColumn": 1,
		"Match": "PasswordRetrievalEmailFrom=REDACTED",
		"Secret": "REDACT",
		"File": "foo/bar/PreferenceDefinitionUUIDs.properties",
		"Commit": "4c43dc22d9aef4e33d283b619530e0644feedda1",
		"Entropy": 4.0535088,
		"Author": "Mr. A",
		"Email": "a@bc.de",
		"Date": "2022-01-17T08:42:06Z",
		"Message": "commit Message A",
		"Tags": [],
		"RuleID": "generic-api-key"
	},
```

same result with copied config:
```json
	{
		"Description": "Generic API Key",
		"StartLine": 4,
		"EndLine": 5,
		"StartColumn": 2,
		"EndColumn": 1,
		"Match": "PasswordRetrievalEmailFrom=REDACTED",
		"Secret": "REDACT",
		"File": "app_sf_responsive/staticfiles/cartridge/lib/com/intershop/b2c/dbmigrate/data/7.3.2.0/preference/PreferenceDefinitionUUIDs.properties",
		"Commit": "5a9467746afff67d92e080b8e12709624baded51",
		"Entropy": 4.0535088,
		"Author": "Mr. A",
		"Email": "a@bc.de",
		"Date": "2022-01-17T08:44:38Z",
		"Message": "commit Message B",
		"Tags": [],
		"RuleID": "generic-api-key"
	},
```

The two commits are adjacent to each other in the history:
![commits](https://user-images.githubusercontent.com/3804909/167779959-09d57588-5c4c-44b8-a35a-9649f951dae1.png)  
However, neither the first result references the 5a9467 commit, nor does the second result reference the 4c43dc commit.

**Comment by Vankog** [comment] 2022-05-11 06:21
Extending on the previous:  
I am not sure about this, but is it intended that the same results are reported over and over again, but for different commits?

The example finding above shows up in the results with 6 instances each, each instance only differing in the commit.   
Further, while there are some overlaps in the results with default config and the results with copied default config, most of the commits are different that they found.  

Is there a way to get consistent result sets?

**Comment by zricethezav** [comment] 2022-05-11 12:17
@Vankog 
I'm unable to reproduce this.

> One strange thing I found is that the results seem to reference the same findings in different commits.
example:

Those examples are from two different commits on two different files. They are not the same findings.

> I am not sure about this, but is it intended that the same results are reported over and over again, but for different commits?

The scan results should be the same ever scan, although the order may be slightly different due to concurrency.


> However, neither the first result references the 5a9467 commit, nor does the second result reference the 4c43dc commit.

I'm doubtful of that, please verify the findings following these steps: https://github.com/zricethezav/gitleaks#verify-findings

What I recommend you do is provide me with a sample repo where you can consistently reproduce this behavior. Closing this issue until then because I'm unable to reproduce this and I have not heard this complaint before.

**Closed by zricethezav** 2022-05-11 12:17 UTC
Labels: bug
