### ISSUE TITLE
[pre-commit hook] An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')

### ISSUE THREAD

**Issue by tarrade** [zricethezav/gitleaks#994] opened 2022-09-30 09:36 UTC
**Describe the bug**
On Ubuntu, and using gitleaks in a pre-commit hooks is cashing at the initialization step

**To Reproduce**
As stated in the doc, in the .pre-commit-commit.yaml add the following
```
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.13.0
    hooks:
      - id: gitleaks
```
Then run:
`pre-commit run --all-files --verbose`

I am getting:
```
[INFO] Installing environment for https://github.com/zricethezav/gitleaks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)
Check the log at /home/jupyter/.cache/pre-commit/pre-commit.log
```

Looking at the logs doesn't give me a message that I can understand
### version information

```
pre-commit version: 2.20.0
git --version: git version 2.37.3
sys.version:
    3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
sys.executable: /opt/conda/envs/jupyter-notebook/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)
```

```
Traceback (most recent call last):
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/languages/golang.py", line 69, in install_environment
    remote = git.get_remote_url(prefix.prefix_dir)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/git.py", line 97, in get_remote_url
    _, out, _ = cmd_output('git', 'config', 'remote.origin.url', cwd=git_root)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)
```

**Expected behavior**
Should install gitleaks and run it for the given github repository. It is working fine with other pre-commit hooks.

**Basic Info (please complete the following information):**
 - OS: 
Distributor ID: Ubuntu  
Description:    Ubuntu 20.04.5 LTS  
Release:        20.04  
Codename:       focal  

 - Gitleaks Version:  v8.13.0
 
 I tried other version but I see the same issue. Seems to be related the way github tried setup and clone the repo

**Additional context**
No access to internet. I am using a proxy server but normally all url needed are whitelisted including github.com
```
git remote -v                                     
origin  https://github.xxxcom/xxx/xx-utils.git (fetch)
origin  https://github.xxx.com/xxx/xx-utils.git (push)
```

the command that the system try to run doesn't seems to be a valid command
`/usr/bin/git config' remote.origin.url`

I didn't find where is the script that try to do the installation. Any suggestion where to look at it to debug this installation issue ?

Thanks

cc @zricethezav

**Comment by tarrade** [comment] 2022-10-03 17:30
seems to be ok:

```
(jupyter-notebook)jupyter@:~/.cache/pre-commit/repors3wlicl$ls -la
total 232
drwx------ 10 jupyter jupyter  4096 Oct  3 19:18 .
drwxrwxr-x 20 jupyter jupyter  4096 Oct  3 19:18 ..
drwxrwxr-x  5 jupyter jupyter  4096 Oct  3 19:18 .git
drwxrwxr-x  4 jupyter jupyter  4096 Oct  3 19:18 .github
-rw-rw-r--  1 jupyter jupyter   195 Oct  3 19:18 .gitignore
-rw-rw-r--  1 jupyter jupyter 72456 Oct  3 19:18 .gitleaksignore
-rw-rw-r--  1 jupyter jupyter   492 Oct  3 19:18 .goreleaser.yml
-rw-rw-r--  1 jupyter jupyter   401 Oct  3 19:18 .pre-commit-hooks.yaml
-rw-rw-r--  1 jupyter jupyter  4291 Oct  3 19:18 CONTRIBUTING.md
-rw-rw-r--  1 jupyter jupyter   502 Oct  3 19:18 Dockerfile
-rw-rw-r--  1 jupyter jupyter  1069 Oct  3 19:18 LICENSE
-rw-rw-r--  1 jupyter jupyter   559 Oct  3 19:18 Makefile
-rw-rw-r--  1 jupyter jupyter 15797 Oct  3 19:18 README.md
drwxrwxr-x  3 jupyter jupyter  4096 Oct  3 19:18 cmd
drwxrwxr-x  2 jupyter jupyter  4096 Oct  3 19:18 config
drwxrwxr-x  3 jupyter jupyter  4096 Oct  3 19:18 detect
-rw-rw-r--  1 jupyter jupyter  1814 Oct  3 19:18 go.mod
-rw-rw-r--  1 jupyter jupyter 62576 Oct  3 19:18 go.sum
-rw-rw-r--  1 jupyter jupyter   611 Oct  3 19:18 main.go
drwxrwxr-x  2 jupyter jupyter  4096 Oct  3 19:18 report
drwxrwxr-x  2 jupyter jupyter  4096 Oct  3 19:18 scripts
drwxrwxr-x  7 jupyter jupyter  4096 Oct  3 19:18 testdata
```

```
(jupyter-notebook)jupyter@:~/.cache/pre-commit/repors3wlicl$git remote -v 
origin  https://github.com/zricethezav/gitleaks (fetch)
origin  https://github.com/zricethezav/gitleaks (push)
```

**Comment by tarrade** [comment] 2022-10-03 17:47
I have the feeling that the script is failing somewhere else and report the wrong issue.

what is done after the repo is clone by the pre-commit hook ? I didn't really find it. 
If I try to use "make" then I see some issues with url redirect blocked by the proxy. This is maybe the main issue or something that I will face later:

(jupyter-notebook)jupyter@:~/.cache/pre-commit/repors3wlicl$make
go test -v ./... --race --cover --coverprofile=cover.out github.com/zricethezav/gitleaks
go: downloading github.com/rs/zerolog v1.26.1
go: downloading github.com/spf13/viper v1.8.1
go: downloading github.com/gitleaks/go-gitdiff v0.8.0
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/lucasjones/reggen v0.0.0-20200904144131-37ba4fa293bb
go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/charmbracelet/lipgloss v0.5.0
go: downloading github.com/fatih/semgroup v1.2.0
go: downloading github.com/h2non/filetype v1.1.3
go: downloading github.com/petar-dambovaliev/aho-corasick v0.0.0-20211021192214-5ab2d9280aa9
detect/utils.go:10:2: github.com/charmbracelet/lipgloss@v0.5.0: Get "https://proxy.golang.org/github.com/charmbracelet/lipgloss/@v/v0.5.0.zip": OpCoCHURLBlocked
detect/detect.go:17:2: github.com/fatih/semgroup@v1.2.0: Get "https://proxy.golang.org/github.com/fatih/semgroup/@v/v1.2.0.zip": OpCoCHURLBlocked
detect/detect.go:18:2: github.com/gitleaks/go-gitdiff@v0.8.0: Get "https://proxy.golang.org/github.com/gitleaks/go-gitdiff/@v/v0.8.0.zip": OpCoCHURLBlocked
detect/detect.go:19:2: github.com/h2non/filetype@v1.1.3: Get "https://proxy.golang.org/github.com/h2non/filetype/@v/v1.1.3.zip": OpCoCHURLBlocked
detect/detect.go:20:2: github.com/petar-dambovaliev/aho-corasick@v0.0.0-20211021192214-5ab2d9280aa9: Get "https://proxy.golang.org/github.com/petar-dambovaliev/aho-corasick/@v/v0.0.0-20211021192214-5ab2d9280aa9.zip": OpCoCHURLBlocked
main.go:7:2: github.com/rs/zerolog@v1.26.1: Get "https://proxy.golang.org/github.com/rs/zerolog/@v/v1.26.1.zip": OpCoCHURLBlocked
main.go:8:2: github.com/rs/zerolog@v1.26.1: Get "https://proxy.golang.org/github.com/rs/zerolog/@v/v1.26.1.zip": OpCoCHURLBlocked
cmd/detect.go:9:2: github.com/spf13/cobra@v1.2.1: Get "https://proxy.golang.org/github.com/spf13/cobra/@v/v1.2.1.zip": OpCoCHURLBlocked
cmd/detect.go:10:2: github.com/spf13/viper@v1.8.1: Get "https://proxy.golang.org/github.com/spf13/viper/@v/v1.8.1.zip": OpCoCHURLBlocked
cmd/generate/secrets/regen.go:6:2: github.com/lucasjones/reggen@v0.0.0-20200904144131-37ba4fa293bb: Get "https://proxy.golang.org/github.com/lucasjones/reggen/@v/v0.0.0-20200904144131-37ba4fa293bb.zip": OpCoCHURLBlocked
make: *** [Makefile:9: test-cover] Error 1 

I will fix the issue with the proxy and try again

**Comment by tarrade** [comment] 2022-10-04 06:55
I am able to trigger the same error using the following code:

```
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pre_commit import git
>>> prefix_prefix_dir="/home/jupyter/.cache/pre-commit/repoa8g_h873"
>>> remote = git.get_remote_url(prefix_prefix_dir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/git.py", line 97, in get_remote_url
    _, out, _ = cmd_output('git', 'config', 'remote.origin.url', cwd=git_root)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
```

I have the same error if instead of gitleak github repo, I am using one of my github repository.

Now, if I tried to mimic what is done in "cmd_output"
- go to the repo
- run `git config remote.origin.url`  output nothing
but if I use:
`git remote -v`
origin  https://github.com/zricethezav/gitleaks (fetch)
origin  https://github.com/zricethezav/gitleaks (push)

I am not an expert but it seems that `git config remote.origin.url` is not returning what is should be (or I don't understand how the command should be run)

```
 git --version
git version 2.37.3
```

**Comment by tarrade** [comment] 2022-10-04 07:53
Ok, I think the issue is related to that. If I pass the --file, then it works:

```
git config -f .git/config --get remote.origin.url
https://github.com/zricethezav/gitleaks
```

For my proxy config, I am setting a  GIT_CONFIG=/home/jupyter/.gitconfig

It seems that in new version "For reading options: read only from the specified file rather than from all available files." [Stackoverflow](https://stackoverflow.com/questions/67708573/how-do-i-use-git-config-environment-variable) the -f option need to be set.

**Comment by weineran** [comment] 2022-10-04 15:44
> I have the same error if instead of gitleak github repo, I am using one of my github repository.

Glad to hear the issue is not specific to gitleaks.

> It seems that in new version "For reading options: read only from the specified file rather than from all available files." [Stackoverflow](https://stackoverflow.com/questions/67708573/how-do-i-use-git-config-environment-variable) the -f option need to be set.

Does that mean you've resolved the issue? Does it make sense to close this issue now?

**Comment by tarrade** [comment] 2022-10-04 18:30
@weineran the issue seems to be either on my git config (still have the issue even if I am not using GIT_CONFIG env variable) or on the pre-commit python utis. It seems not related to gitleaks directly.

I will close this ticket. The discussion is continuing here: https://github.com/pre-commit/pre-commit/issues/2540

**Closed** 2022-10-04 18:30 UTC
Labels: bug

**Comment by tarrade** [comment] 2022-10-04 20:20
Issue fixed, in my case having a env variable GIT_CONFIG was creating the issue. An empty value is not a valid solution as well. The env variable should not be created or unset.

**Comment by weineran** [comment] 2022-10-05 01:36
Thanks for posting the solution @tarrade !
