### ISSUE TITLE
Question: Prevent secret duplication

### ISSUE THREAD

**Issue by m1nkeh** [zricethezav/gitleaks#371] opened 2020-04-19 08:47 UTC
Hi,

Is there a way of writing a rule that will match to the secret: `G5CdMajvIpyyZ020VRddccTxkX/GjXjq5ID52+nrghg=`

but not match to the secret: `V2agTeXn6YXfUWhrDSJlVnwbrXMSRfCmi4rlrznOOEaG5CdMajvIpyyZ020VRddccTxkX/GjXjq5ID52+nrghg==`

So far i have:
```
[[rules]]
	description = "SharedAccessKey"
	regex = '''[A-z0-9\+\/]{43}='''
	tags = ["SharedAccessKey"]
```

But due to the first string being a substring of the second value, i get false-positives..
![image](https://user-images.githubusercontent.com/13475141/79683579-6bae2180-822b-11ea-8c53-94aa83f84589.png)

Is there a way to prevent this?

**Comment by zricethezav** [comment] 2020-05-09 14:46
@m1nkeh you could make use of the whitelist table within a rule. For example: https://github.com/zricethezav/gitleaks/blob/master/test_data/test_configs/aws_key_aws_whitelisted.toml
```
[[rules]]
    description = "AWS Manager ID"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]
        [[rules.whitelist]]
            regex = '''AKIAIO5FODNN7EXAMPLE.*'''
            description = "ignore aws key"
```
This rule will match all AWS Manager keys besides the example key defined in the whitelist: `AKIAIO5FODNN7EXAMPLE`

**Comment by m1nkeh** [comment] 2020-05-09 14:55
I tried that.. I had hoped that I could put another regex in the whitelist, but it didn’t work.

I guess the challenge is two fold because they are both random strings, and I can’t whitelist a string larger than the string that has been hit.

I worked on this for a while since I posted the question, didn’t get a satisfactory irking answer unfortunately :/

**Comment by zricethezav** [comment] 2020-05-09 15:20
@m1nkeh Is the length of the larger string known?

**Comment by m1nkeh** [comment] 2020-05-11 15:26
> @m1nkeh Is the length of the larger string known?

Yes absolutely, i think it's about 80 or 90 characters, i can check the regex on my other computer.. but yeah, it's around double.. looks similar to the original post.

**Comment by zricethezav** [comment] 2021-11-24 21:13
Closing this issue as this is not a bug but rather a configuration issue that can be tuned

**Closed by zricethezav** 2021-11-24 21:13 UTC

**Comment by m1nkeh** [comment] 2021-12-01 22:31
Never really got an answer though, happy to leave it closed though as it's no longer at all relevant to me 👍 🙂
