### ISSUE TITLE
--no-git option does not seem to be working properly

### ISSUE THREAD

**Issue by visionarchitect** [zricethezav/gitleaks#751] opened 2021-12-13 12:29 UTC
**Describe the bug**
I have large solution with many leaks both in git history and in current version
When I run gitleaks detect with --no-git option (which I assume should recursively scan all folders) no leaks are returned and scan finishes really fast

**To Reproduce**
Use Webgoat project and run default config with detect and --no-git 

**Expected behavior**
Recursively go through all folders and report leaks

**Screenshots**
![image](https://user-images.githubusercontent.com/3788334/145812430-60b3a479-6ee2-4359-a832-24157b30d575.png)

**Basic Info (please complete the following information):**
 - OS: Windows
 - Gitleaks Version: 8.2

**Comment by visionarchitect** [comment] 2021-12-13 13:17
Found it!


if !godocutil.IsText(b) {
				return nil
			}

Normal text files are identified as binary and skipped!
Works much better with this code removed from files.go

**Comment by visionarchitect** [comment] 2021-12-13 14:42
Ok this is what I did to debug
`if !godocutil.IsText(b) {
				fmt.Println(pa)
				return nil
			}`
			
![image](https://user-images.githubusercontent.com/3788334/145832528-9e3f62af-5d90-4a46-b9b6-f8681f744c5d.png)

And here is what I got
[webgoat.txt](https://github.com/zricethezav/gitleaks/files/7704579/webgoat.txt)

**Comment by zricethezav** [comment] 2021-12-13 14:52
@visionarchitect hmmm that's odd, https://go.dev/play/p/ZUjmtCvMLPw seems to be working. I can try reproducing this locally after work. Maybe 
```
			if !godocutil.IsText(b) {
				return nil
			}
```
should be removed.

FWIW this is the doc for `IsText(b)` https://pkg.go.dev/golang.org/x/tools/godoc/util#IsText

**Comment by visionarchitect** [comment] 2021-12-13 14:56
Maybe this is Windows specific. 
I will try Linux later today. This have occurred on different desktops and VM's today. (well I am not sure if exactly this but I was trying to instruct some people to use gitleaks for their repo and I failed to show them it works)

**Comment by visionarchitect** [comment] 2021-12-13 15:07
Maybe you should use 
IsTextFile() instead

**Comment by zricethezav** [comment] 2021-12-13 15:10
> Maybe you should use
IsTextFile() instead

I encourage you to look at the code for `IsTextFile`, all that that function is doing is checking the file extension and opening the file then calling `IsText`

**Comment by zricethezav** [comment] 2021-12-13 15:11
@visionarchitect 
> Maybe this is Windows specific.

😬 

> I will try Linux later today.  

Let me know what you find! Thanks 😄

**Comment by visionarchitect** [comment] 2021-12-13 15:52
looks like linux/windows issue - probably you can't see it on mac too
Same repo
Linux:
![image](https://user-images.githubusercontent.com/3788334/145843886-35c48483-a485-4adb-990f-599f477a99cd.png)

Windows:
![image](https://user-images.githubusercontent.com/3788334/145844065-502e720a-c19a-4de2-a5d2-f9f3e6824c58.png)

**Comment by KameleonSec** [comment] 2022-01-03 10:15
Same issue here, trying to upgrade to gitleaks_8.2.1_linux_x64 there are allot of files that aren't beeing scanned and leaks that are missed.
Running gitleaks-linux-amd64 with --no-git option finds leaks that the most recent versions do not.

**Comment by mark-ship-it** [comment] 2022-01-05 19:36
I can confirm this also breaks in a `.pre-commit-config.yaml` file also:

```
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.5
    hooks:
    - id: gitleaks
      args: ['detect', '--redact']
    - id: gitleaks
      args: ['detect', '--no-git']
```

Error: unknown flag: --no-git

**Comment by zricethezav** [comment] 2022-01-07 18:38
@visionarchitect closing this issue with the release of v8.2.7, reopen if it doesn't fix it for ya

**Closed by zricethezav** 2022-01-07 18:38 UTC
Labels: bug
