### ISSUE TITLE
Whitelisting applying over multiple matches

### ISSUE THREAD

**Issue by blindphaze** [zricethezav/gitleaks#346] opened 2020-02-26 22:18 UTC
**Describe the bug**
When creating a whitelist rule, the whitelist is applying over multiple lines instead of just a single line where the match was. 

**To Reproduce**
Use the rule.txt file provided as a configuration against values.txt to note that there are three leaks detected. Then, uncomment the whitelist rule and note that now 0 leaks are detected. 
[rule.txt](https://github.com/zricethezav/gitleaks/files/4258429/rule.txt)
[values.txt](https://github.com/zricethezav/gitleaks/files/4258430/values.txt)

**Expected behavior**
The whitelist should only be applying against each individual matching instead of applying over multiple matches that have been made.

**Basic Info (please complete the following information):**
 - OS: ubuntu 18.04
 - Gitleaks Version: current master from github

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment] 2020-02-26 22:33
I'm unable to reproduce this. I see the three leaks and then after uncommenting the whitelist I see two as expected

**Comment by zricethezav** [comment] 2020-02-26 22:36
No whitelist:
```
{"line":"TOKEN_KEY 'my-token-here'","offender":"TOKEN_KEY 'my-token-here'","commit":"fde438efb0c513cbaed6a3b61049f4c9423fffc5","repo":"tmp","rule":"Generic Credential","commitMessage":"init\n","author":"Zach Rice","email":"zrice@gitlab.com","file":"hello.txt","date":"2020-02-26T17:34:40-05:00","tags":"key, API, generic"}
{"line":"OAUTH_CLIENT_ID 'my-user'","offender":"AUTH_CLIENT_ID 'my-user'","commit":"fde438efb0c513cbaed6a3b61049f4c9423fffc5","repo":"tmp","rule":"Generic Credential","commitMessage":"init\n","author":"Zach Rice","email":"zrice@gitlab.com","file":"hello.txt","date":"2020-02-26T17:34:40-05:00","tags":"key, API, generic"}
{"line":"secretName 'secret-files'","offender":"secretName 'secret-files'","commit":"fde438efb0c513cbaed6a3b61049f4c9423fffc5","repo":"tmp","rule":"Generic Credential","commitMessage":"init\n","author":"Zach Rice","email":"zrice@gitlab.com","file":"hello.txt","date":"2020-02-26T17:34:40-05:00","tags":"key, API, generic"}
WARN[2020-02-26T17:36:06-05:00] 3 leaks detected. 1 commits audited in 908 microseconds 
```


With whitelist:
```
{"line":"OAUTH_CLIENT_ID 'my-user'","offender":"AUTH_CLIENT_ID 'my-user'","commit":"fde438efb0c513cbaed6a3b61049f4c9423fffc5","repo":"tmp","rule":"Generic Credential","commitMessage":"init\n","author":"Zach Rice","email":"zrice@gitlab.com","file":"hello.txt","date":"2020-02-26T17:34:40-05:00","tags":"key, API, generic"}
{"line":"secretName 'secret-files'","offender":"secretName 'secret-files'","commit":"fde438efb0c513cbaed6a3b61049f4c9423fffc5","repo":"tmp","rule":"Generic Credential","commitMessage":"init\n","author":"Zach Rice","email":"zrice@gitlab.com","file":"hello.txt","date":"2020-02-26T17:34:40-05:00","tags":"key, API, generic"}
WARN[2020-02-26T17:35:02-05:00] 2 leaks detected. 1 commits audited in 824 microseconds 
```

**Comment by zricethezav** [comment] 2020-02-26 22:38
Please provide the command you are running and output

**Comment by blindphaze** [comment] 2020-02-28 16:04
@zricethezav Sorry for taking so long to get back to you, here is a more detailed output.  I uploaded the files to a public repo to make this easier as well

Here is a first run without the whitelist rule enabled: (6 findings)

```
$ ~/go/src/gitleaks/gitleaks --repo=https://github.com/blindphaze/leak-test.git --config=rule.txt -v
INFO[2020-02-28T10:00:50-06:00] cloning... https://github.com/blindphaze/leak-test.git 
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Compressing objects: 100% (5/5), done.
Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
{"line":"TOKEN_KEY 'my-token-here'","offender":"TOKEN_KEY 'my-token-here'","commit":"1455d813b6dabee5fabb3633065f39a808dcab06","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create values.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"values.txt","date":"2020-02-28T10:00:13-06:00","tags":"key, API, generic"}
{"line":"OAUTH_CLIENT_ID 'my-user'","offender":"AUTH_CLIENT_ID 'my-user'","commit":"1455d813b6dabee5fabb3633065f39a808dcab06","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create values.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"values.txt","date":"2020-02-28T10:00:13-06:00","tags":"key, API, generic"}
{"line":"  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|\"][0-9a-zA-Z-_!{}/=]{4,120}['|\"]'''","offender":"dbpasswd|api_key|apikey|secret|","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
{"line":"  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|\"][0-9a-zA-Z-_!{}/=]{4,120}['|\"]'''","offender":"key|api|password|pw|auth|","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
{"line":"  tags = [\"key\", \"API\", \"generic\"]","offender":"key\", \"API\", \"generic\"","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
{"line":"secretName 'secret-files'","offender":"secretName 'secret-files'","commit":"1455d813b6dabee5fabb3633065f39a808dcab06","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create values.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"values.txt","date":"2020-02-28T10:00:13-06:00","tags":"key, API, generic"}
WARN[2020-02-28T10:00:51-06:00] 6 leaks detected. 2 commits audited in 1 millisecond 66 microseconds 

```
```
$ cat rule.txt 
[[rules]]
  description = "Generic Credential"
  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|"][0-9a-zA-Z-_!{}/=]{4,120}['|"]'''
  tags = ["key", "API", "generic"]
#     [[rules.whitelist]]
#       regex = '''my-token-here'''

```

Now I uncomment the rules.whitelist lines and we see there are now only 3 findings:

```
~/go/src/leak-test$ ~/go/src/gitleaks/gitleaks --repo=https://github.com/blindphaze/leak-test.git --config=rule.txt -v
INFO[2020-02-28T10:02:14-06:00] cloning... https://github.com/blindphaze/leak-test.git 
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Compressing objects: 100% (5/5), done.
Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
{"line":"  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|\"][0-9a-zA-Z-_!{}/=]{4,120}['|\"]'''","offender":"dbpasswd|api_key|apikey|secret|","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
{"line":"  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|\"][0-9a-zA-Z-_!{}/=]{4,120}['|\"]'''","offender":"key|api|password|pw|auth|","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
{"line":"  tags = [\"key\", \"API\", \"generic\"]","offender":"key\", \"API\", \"generic\"","commit":"2cd2436c8c6f8c1e013fd8ffd8ca16ca1de0ab1d","repo":"leak-test.git","rule":"Generic Credential","commitMessage":"Create rule.txt","author":"blindphaze","email":"blindphaze@users.noreply.github.com","file":"rule.txt","date":"2020-02-28T09:53:43-06:00","tags":"key, API, generic"}
WARN[2020-02-28T10:02:14-06:00] 3 leaks detected. 2 commits audited in 1 millisecond 100 microseconds 
```
```
$ cat rule.txt 
[[rules]]
  description = "Generic Credential"
  regex = '''(?i)(dbpasswd|api_key|apikey|secret|key|api|password|pw|auth|token|pass)(.{0,20})?['|"][0-9a-zA-Z-_!{}/=]{4,120}['|"]'''
  tags = ["key", "API", "generic"]
     [[rules.whitelist]]
       regex = '''my-token-here'''
```

**Comment by blindphaze** [comment] 2020-02-28 16:43
I have pulled in the lastest commits and rebuilt the binary, I am no longer seeing this issue.  
It looks like I was on commit e7fbcf53338e283bd4c92ecb1e59de7a6df5fa14 when seeing this issue.

**Comment by zricethezav** [comment] 2020-02-28 17:06
Perfect, glad the latest version fixed it. Closing this issue out. Reopen if needed. Cheers

**Closed by zricethezav** 2020-02-28 17:06 UTC
Labels: bug
