### ISSUE TITLE
gitleaks hangs on protect command if there are no files to scan

### ISSUE THREAD

**Issue by galmalka** [zricethezav/gitleaks#724] opened 2021-11-30 16:46 UTC
**Describe the bug**
When running protect command, if there are no files to scan, the process hangs. It happens if there are no unstaged files without the --staged flag and vice versa.

**To Reproduce**
Run 'gitleaks protect' without any unstaged changes OR 'gitleaks protect --staged' without any staged changes.

**Expected behavior**
The process should return without any errors

**Screenshots**
N.A

**Basic Info (please complete the following information):**
 - OS: macOS Monterey
 - Gitleaks Version: 8.0.4

**Additional context**
Seems to work on 8.0.3 (and previous versions).

cc @zricethezav

**Comment by zricethezav** [comment] 2021-11-30 16:49
```
➜  ~/code/gitleaks (master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
➜  ~/code/gitleaks (master) ./gitleaks protect

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:48AM INF no leaks found
10:48AM INF scan duration: 13.515985ms
➜  ~/code/gitleaks (master)
```

Seems to be working for me, could post your commands/output like I did?

**Comment by zricethezav** [comment] 2021-11-30 18:40
This could be related to https://github.com/zricethezav/gitleaks/issues/722 although I doubt it, could you please try `v8.0.6` and see if it is fixed?

**Comment by galmalka** [comment] 2021-11-30 22:22
Thanks for the quick reply.
First of all, here is the output (with debug logging):
```
➜  ~/code git:(test) git status
On branch test
nothing to commit, working tree clean
➜  ~/code git:(test) gitleaks protect --log-level debug

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

12:18AM DBG Using existing gitleaks config .gitleaks.toml
12:18AM DBG executing: /usr/local/bin/git -C . diff -U0 .
```
This is where the process seems to hang.

I checked with version 8.0.6 and it works, but then I also downloaded version 8.0.4 from the releases and when I run the bin from the download directory it works as well (for any version).
So now it seems that the issue only occurs for the version installed by homebrew on mac.

**Comment by zricethezav** [comment] 2021-11-30 22:46
@galmalka thank you for the context. Let's keep this open until its verified on v8.0.6 installed via brew.

**Comment by zricethezav** [comment] 2021-12-01 17:10
@galmalka now that https://formulae.brew.sh/formula/gitleaks is on v8.0.6, could you see if this is still an issue for you? If it's not then we can close this issue

**Comment by veleek** [comment] 2021-12-02 00:55
@zricethezav - I'm seeing this same problem on my end in two different situations.

1. Cloned git repo and build on Windows.  Then run `gitleaks protect -v --staged --log-level=debug` hangs same as above.
   ```
    > gitleaks protect -v --staged --log-level=debug   

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

   4:48PM DBG Using existing gitleaks config .gitleaks.toml
   4:48PM DBG executing: C:\Program Files\Git\cmd\git.exe -C . diff -U0 --staged .
   ```
2. Running as part of pre-commit in a GitHub action on a Linux machine.  Can't get the exact same output, but it does appear to hang indefinitely (private repo so I can't point to a representative build check).

**Comment by zricethezav** [comment] 2021-12-02 00:59
@veleek hmm that's troubling, what version of gitleaks are you using?

**Comment by veleek** [comment] 2021-12-02 01:00
Just cloned moments ago.  Here's another repro with a brand new empty repo.

```

   C:\src  cd foo
   C:\src\foo  git init
Initialized empty Git repository in C:/src/foo/.git/
   C:\src\foo  master  gitleaks protect -v --log-level=debug

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

4:59PM DBG No gitleaks config found, writing default gitleaks config to .gitleaks.toml
4:59PM DBG executing: C:\Program Files\Git\cmd\git.exe -C . diff -U0 .
4:59PM FTL Interrupt signal received. Exiting...
   C:\src\foo  master  gitleaks version
v8.0.6
```

**Comment by zricethezav** [comment] 2021-12-02 01:01
damn, mind sharing what version of `git` you're using?

**Comment by veleek** [comment] 2021-12-02 01:02
```
> git version
git version 2.32.0.windows.2
```

**Comment by veleek** [comment] 2021-12-02 01:06
Git version being used on GitHubActions build machine is `git version 2.34.1`.

**Comment by zricethezav** [comment] 2021-12-02 01:08
Dang, I wish I could reproduce this. I'll try to figure this out by rubber ducky-ing it but if anyone has steps to reproduce on a Mac that would be great.

**Comment by veleek** [comment] 2021-12-02 01:15
I'm debugging through the `GitDiff` function to see if I can see.  May be related to #722, but seems odd why it would be.

**Comment by veleek** [comment] 2021-12-02 01:24
When there are no files, `GitDiff` returns an empty channel that doesn't appear to be closed.  

Calling `range files` on the channel hangs here: https://github.com/zricethezav/gitleaks/blob/master/detect/git.go#L22

**Comment by zricethezav** [comment] 2021-12-02 01:25
I have a feeling it might have to do with https://github.com/gitleaks/go-gitdiff/blob/master/gitdiff/parser.go#L18. Can't devote time tonight to look at this but will continue in the morning. Help is welcomed! Thanks for digging more into this @veleek

**Comment by zricethezav** [comment] 2021-12-02 01:26
> Calling range files on the channel hangs here: https://github.com/zricethezav/gitleaks/blob/master/detect/git.go#L22

Okay last thought for the night, then 
> I have a feeling it might have to do with https://github.com/gitleaks/go-gitdiff/blob/master/gitdiff/parser.go#L18.  

Is probably right, the channel is never closed and nothing is sent to it

**Comment by veleek** [comment] 2021-12-02 01:26
Cool, I can dig in more tomorrow if you need it to.  Thanks for the quick response!

**Comment by zricethezav** [comment] 2021-12-02 01:32
@veleek okay sorry this is my actual last thought:

https://github.com/gitleaks/go-gitdiff/blob/master/gitdiff/parser.go#L22-L27 needs a `close(out)` before returning.

**Comment by zricethezav** [comment] 2021-12-02 02:46
@veleek I know I said I was done for the night but uhm well I lied. 

Would you mind pulling the `bump-git-diff` branch https://github.com/zricethezav/gitleaks/tree/bump-git-diff and see if the issue is fixed?

**Comment by galmalka** [comment] 2021-12-02 07:16
@zricethezav, I pulled the `bump-git-diff` branch. This version works, but I did notice the problem only for the version installed by homebrew.
Do you know why this might happen and how to reproduce for locally built versions?

**Comment by zricethezav** [comment] 2021-12-02 14:02
@galmalka 
>but I did notice the problem only for the version installed by homebrew.

Okay I figured it out. I committed a big no-no in that when I was developing the go-gitdiff dependency I altered the code in my `go/pkg/mod` so the binaries in the release had the [`close(out)` statement](https://github.com/gitleaks/go-gitdiff/blob/master/gitdiff/parser.go#L23) where the binary built by brew, did not. 

Lesson learned, I'll stop being lazy and use `replace` in my go.mod file

**Comment by zricethezav** [comment] 2021-12-02 14:30
leaving this open until confirmed working on v8.0.7 brew

**Comment by veleek** [comment] 2021-12-03 20:46
I haven't tried the homebrew version, but it fixes the problem on my box.

**Comment by zricethezav** [comment] 2021-12-03 20:52
Good deal, I think I'll be closing this then. Feel free to reopen if the problem persists

**Closed by zricethezav** 2021-12-03 20:52 UTC
Labels: bug

**Comment by galmalka** [comment] 2021-12-04 15:17
Works from homebrew, thanks @zricethezav!
